version: '3'
services:
  littleledger:
    image: gps949/littleledger:latest
    container_name: littleledger
    restart: always
    ports:
     - 3456:3456
    environment:
      LL_USE: <替换为用户名>
      LL_PWD: <替换为密码>
     volumes:
     - ./data:/home/littleledger/ledgers gps949
    privileged: true
