version: '3'
services:
  littleledger:
    image: gps949/littleledger:latest
    container_name: littleledger
    restart: always
    ports:
     - 3456:3456
    environment:
      LL_USER: ""
      LL_PWD: ""
     volumes:
     - /tmp:/home/littleledger/ledgers
    privileged: true
